### ISSUE TITLE
Running Dash.NET from scripts

### ISSUE THREAD

**Issue by kMutagene** [plotly/Dash.NET#17]
With Giraffe - and therefore asp.netcore - Dash.NET has to be an application (at least to my knowledge we can not use these libraries in a scripting environment). It might be worth to investigate adding support for a lightweight server such as [suave](https://github.com/SuaveIO/suave) to enable Dash.NET apps from within a single script file

**Comment by kMutagene** [comment]
This would also need a separation into a `Dash.NET.Core` package, without server side dependencies, and `Dash.NET.Giraffe` and `Dash.NET.Suave` to create the server implementation specific stuff. 

As another upside of making Dash.NET runnable from .fsx scripts it will be possible to generate rich documentation scripts with hover infos and better syntax highlighting, which is currently not possible as FSharp.Formatting can only format script files.

**Comment by jackparmer** [comment]
@ademar and I connected by email a few months ago. He wasn't available then but maybe his availability has changed 😉

**Comment by ademar** [comment]
I'm available now. I'll dig into it and start familiarizing with the codebase.

**Comment by ademar** [comment]
Hi Kevin,

I've pushed the work to the branch "issue-17". Here is a description of what I have done.

- Moved Giraffe code, files View.fs and  DashApp.fs to its own project Dash.NET.Giraffe.
- Created a new project Dash.NET.Suave using the Suave web server; basically reproduced the code from the Giraffe project since they are very similar.
- Created two example projects Dash.NET.Giraffe.Example and Dash.NET.Suave.Example

Notes:
- The Suave app works fine as an application and a script (doing dotnet fsi Script.fs). It does not work in the Visual Studio 2019 F# interactive console as this is broken atm (see for example https://github.com/dotnet/fsharp/issues/11622). They break this with every VS update.

- The Giraffe app does not work for me at the moment. We can see Kestrel booting up messages but it fails with "System.IO.IOException: Cannot determine the frame size or a corrupted frame was received."

- I've used our own Suave.Html for the html bits in the Suave app. I realize I can probably use Feliz.Engine instead as it seems to be your intention going forward and it will minimize dependencies.

- There is still some duplication of code we can eliminate.

- I've removed non Dash properties from the DashConfig record; wasn't sure on how to deal with it - I think we could just pass them in in the DashApp.run call.

Let me know your thoughts and what else can be improved or fixed.
